---
title: "SiMLR vs RGCCA: Breast cancer omics data"
output: html_document
---

## Naive test of two dimensionality reduction methods with respect to breast cancer omics data prediction


```{r}
library( ANTsR )
library( RGCCA )
library( measures )
library( survival )
library( survcomp )
### collect data
# http://acgt.cs.tau.ac.il/multi_omic_benchmark/download.html
fns = Sys.glob( "~/Downloads/Breast/*txt" )
clin <- read.table( fns[4],stringsAsFactors = FALSE , header=TRUE)
m1 = t( read.table( fns[1], header=T ) )
m2 = t( read.table( fns[2], header=T ) )
m3 = t( read.table( fns[3], header=T ) )
isTrain = rep( TRUE, nrow( m1 ) )
isTrain[ sample( 1:length(isTrain), 21 ) ] = FALSE
trainer = list( m1[isTrain,], m2[isTrain, ], m3[isTrain,], clin[isTrain,2:3] )
tester = list( m1[!isTrain,], m2[!isTrain, ], m3[!isTrain,], clin[!isTrain,2:3] )
breast = list( data.train = trainer, data.test = tester )
locsee = as.integer( Sys.time() )
print( locsee )
set.seed( locsee )
mixAlg =  'ica'
mycon = 'Grassmann'
nComponents = 2
nBootStrapRuns = 20
myresults = data.frame( simCox = NA, rgCox = NA )
typTe = breast$data.test[[4]]
typTr = breast$data.train[[4]]
nnn = round( nrow( breast$data.train[[1]] ) * 0.95 )
for ( it in 1:nBootStrapRuns ) {
  # resampling/bootstrapping
  trainData = list()
  sss = sample( 1:nrow( breast$data.train[[1]] ), nnn, replace=FALSE )
  for ( k in 1:3 )
    trainData[[k]] = breast$data.train[[k]][sss,]
  trainData[[4]] = antsrimpute( breast$data.train[[4]][sss,], median )
  # parameters were set s.t. a small amount of gaussian smoothing results
  if ( ! exists( "regs" ) ) regs = regularizeSimlr( trainData, fraction=0.025,  sigma=c(3,3,3,1) )
  # below will give a warning about number of components but ok to ignore
  initu = initializeSimlr( trainData, nComponents, jointReduction = FALSE, uAlgorithm = mixAlg )
  sparVals = c( 0.88, 0.88, 0.88, 0.5 ) # these lead to roughly similar sparseness
  sparVals2 = c( 0.2, 0.2, 0.2, 1 ) # across both SiMLR and RGCCA
  simresult = simlr(
    trainData,
    regs,
    iterations = 20,
    sparsenessQuantiles = sparVals,
    initialUMatrix = initu,
    mixAlg = mixAlg,
    energyType = 'regression',
    optimizationStyle = 'mixed',
    verbose = TRUE
    )

  proj1 = trainData[[1]] %*% simresult$v[[1]]
  proj2 = trainData[[2]] %*% simresult$v[[2]]
  proj3 = trainData[[3]] %*% simresult$v[[3]]
  trdf = data.frame( proj1=proj1, proj2=proj2, proj3=proj3 )
  proj1 = (breast$data.test[[1]] %*% simresult$v[[1]])
  proj2 = (breast$data.test[[2]] %*% simresult$v[[2]])
  proj3 = (breast$data.test[[3]] %*% simresult$v[[3]])
  tedf = data.frame( proj1=proj1, proj2=proj2 , proj3=proj3 )
  trdf$Survival = antsrimpute( typTr[sss,1] )
  trdf$Death = antsrimpute(typTr[sss,2], FUN=median )
  tedf$Survival = typTe[,1]
  tedf$Death = typTe[,2]
  coxFit <- coxph(Surv(time = Survival , event = Death) ~ . , data = trdf )
  pred_validation = predict( coxFit, newdata = tedf )
  # higher values are better - like a rank correlation
  cindex_validation1 = survcomp::concordance.index(pred_validation,
    surv.time  = tedf$Survival,
    surv.event = tedf$Death, method='noether' )
  myresults[it,1] = cindex_validation1$c.index
  cindex_validation1$c.index

#  simlrResult = caret::confusionMatrix( typTe, predSimlr )
  # now do RGCCA
  myrgcca = sgcca( # this initializes with SVD
            A = trainData,
            C = 1 - diag( length( trainData ) ), # cca-like
            c1 = sparVals2,  # set to roughly match simlr
            ncomp = c( nComponents, nComponents, nComponents, 2 ),
            scale = TRUE,
            verbose = FALSE )

  proj1 = trainData[[1]] %*% myrgcca$a[[1]]
  proj2 = trainData[[2]] %*% myrgcca$a[[2]]
  proj3 = trainData[[3]] %*% myrgcca$a[[3]]
  trdf = data.frame( proj1=proj1, proj2=proj2, proj3=proj3 )
  proj1 = antsrimpute(breast$data.test[[1]] %*% myrgcca$a[[1]])
  proj2 = antsrimpute(breast$data.test[[2]] %*% myrgcca$a[[2]])
  proj3 = antsrimpute(breast$data.test[[3]] %*% myrgcca$a[[3]])
  tedf = data.frame( proj1=proj1, proj2=proj2 , proj3=proj3 )
  trdf$Survival = antsrimpute( typTr[sss,1] )
  trdf$Death = antsrimpute(typTr[sss,2], FUN=median )
  tedf$Survival = typTe[,1]
  tedf$Death = typTe[,2]
  coxFit <- coxph(Surv(time = Survival , event = Death) ~ . , data = trdf )
  pred_validation = predict( coxFit, newdata = tedf )
  cindex_validation2 = survcomp::concordance.index(pred_validation,
    surv.time  = tedf$Survival,
    surv.event = tedf$Death, method = "noether")
  myresults[it,2] = cindex_validation2$c.index
  print( myresults[it,] )


  }
message( "Compare concordance indices" )
print( t.test( myresults[,1], myresults[,2], paired=T ) )
print( colMeans( myresults ) )
##############################
```


```{r}
knitr::kable( myresults )
```
